import type { Metadata } from "next";
import "../globals.css";
import { IRANSans } from "../fonts";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${IRANSans.className} h-screen relative bg-[var(--custom-background-color)] bg-fixed bg-cover bg-center bg-no-repeat antialiased`}
        style={{
          backgroundImage: "var(--custom-background-image)",
        }}
      >
        <header className="flex justify-center absolute top-0 right-1/2 translate-x-1/2">
          <div className="py-5">
            <Image
              src="/logo.png"
              alt="Logo"
              className="md:w-50"
              width={150}
              height={100}
              quality={50}
            />
          </div>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
