import type { Metadata } from "next";
import "../globals.css";
import { IRANSans } from "../fonts";
import Image from "next/image";
import Navbar from "@/components/dashboard/menu/navbar/Navbar";
import DashboardMenu from "@/components/dashboard/menu/DashboardMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${IRANSans.className} h-screen relative bg-[var(--custom-background-color)] bg-fixed bg-cover bg-center bg-no-repeat antialiased`}
        style={{
          backgroundImage: "var(--custom-background-image)",
        }}
      >
        <DashboardMenu />
        <header className="flex justify-center absolute top-0 right-1/2 translate-x-1/2"></header>
        <main className="lg:mr-70">{children}</main>
      </body>
    </html>
  );
}
