import type { Metadata } from "next";
import "./globals.css";
import { IRANSans } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${IRANSans.className} h-screen bg-[var(--custom-background-color)] bg-fixed bg-cover bg-center bg-no-repeat antialiased`}
        style={{
          backgroundImage: "var(--custom-background-image)",
        }}
      >
        {children}
      </body>
    </html>
  );
}
